export const GET_USER_INFOS = 'GET_USER_INFOS'
export const GET_USER_INFOS_SUCCESS = 'GET_USER_INFOS_SUCCESS';
export const GET_USER_INFOS_ERROR = 'GET_USER_INFOS_ERROR';
export const GET_USER_INFOS_CANCEL = 'GET_USER_INFOS_CANCEL';
export const GET_REPOS_NUMBER = 'GET_REPOS_NUMBER';